[#84] Support saving and loading
JeOhLee/MyLittleFont pull request #100
Opened 2017-06-01 11:51 UTC by hangpark

See #84.

2017-06-01 11:57 UTC, bimak-server approved these changes
👍 

㊗️ Congratulations for the 💯th iss/pr ㊗️

2017-06-02 07:51 UTC, xeoh requested changes

2017-06-02 07:51 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontItem.java
> +  private FontItem(double curve, double roundness, double weight, double width) {
Why do we need this constructor?

2017-06-02 07:51 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/MainActivity.java
> +            new DatabaseOpenHelper(getApplicationContext())
Why don't we hold DBhelper in MainActivity? Loading multiple helper object every time we save seems inefficient.

2017-06-02 07:51 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/util/DatabaseOpenHelper.java
> +      "CREATE TABLE " + TABLE_NAME + " ("
Hard to read type of each attribute.

```java
"CREATE TABLE " + TABLE_NAME + " ("
            + KEY_ID        + " INTEGER PRIMARY KEY AUTOINCREMENT, "
            + KEY_NAME      + " TEXT, "
            + KEY_DATETIME  + " DATETIME DEFAULT CURRENT_TIMESTAMP, "
            + KEY_CURVE     + " REAL, "
            + KEY_ROUNDNESS + " REAL, "
            + KEY_WEIGHT    + " REAL, "
            + KEY_WIDTH     + " REAL);";
```

2017-06-02 07:51 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/util/DatabaseOpenHelper.java
> +    getWritableDatabase().execSQL(ROW_DELETE + id);
```java
String ROW_DELETE = "DELETE FROM %s WHERE %d = %d";
execSQL(String.format(ROW_DELETE, TABLE_NAME, KEY_ID, id));
```

2017-06-02 07:51 UTC, JeOhLee commented
Any way congrat for 💯th iss/pr

2017-06-03 10:11 UTC, xeoh approved these changes
👍

2017-06-03 10:11 UTC, merged