[#32] Implement character loader
JeOhLee/MyLittleFont pull request #37
Opened 2017-04-07 15:38 UTC by JeOhLee

Implement character loader(#32).

### 1. ```Hangul``` Enum class
```Hangul``` Enum represent Hangul UNICODE.

### 2. ```CharacterLoader```
Load ```HangulCharacter``` subclasses from ```Hangul```

2017-04-08 08:52 UTC, bimak-server approved these changes
👍

2017-04-08 08:59 UTC, hangpark requested changes

2017-04-08 08:59 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +    Alert.log(Hangul.class, String.format("%x", value));
Remove this line.

2017-04-08 09:16 UTC, hangpark requested changes
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> + * HangulCharacter Loader.
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> + * <p> Every HangulCharacter classes are loaded through this class.
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> +   * Get HangulCharacter class from Hangul enum class.
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> +   * @return Correspond HangulCharacter class.
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +   * Get Hangul enum class from UNICODE value.
Use JavaDoc reference.

2017-04-08 09:16 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +   * @return Correspond Hangul enum class
Use JavaDoc reference.

2017-04-10 03:10 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> + * HangulCharacter Loader.
done.

2017-04-10 03:11 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> + * <p> Every HangulCharacter classes are loaded through this class.
done.

2017-04-10 03:11 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> +   * Get HangulCharacter class from Hangul enum class.
done.

2017-04-10 03:11 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/CharacterLoader.java
> +   * @return Correspond HangulCharacter class.
done.

2017-04-10 03:11 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +   * Get Hangul enum class from UNICODE value.
done.

2017-04-10 03:11 UTC, xeoh commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +   * @return Correspond Hangul enum class
done.

2017-04-30 12:28 UTC, hangpark requested changes
Change `GIYOUK` to `GIYEOK`.

2017-04-30 12:28 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_GIYOUK        ("", 0x11A8),
`FIN_GIYEOK`

2017-04-30 12:28 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_SS_GIYOUK     ("", 0x11A9),
`FIN_SS_GIYEOK`

2017-04-30 12:28 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_GIYOUK_SIOT   ("", 0x11AA),
`FIN_GIYEOK_SIOT`

2017-04-30 12:28 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_RIEUL_GIYOUK  ("", 0x11B0),
`FIN_RIEUL_GIYEOK`

2017-05-01 04:00 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_GIYOUK        ("", 0x11A8),
Done.

2017-05-01 04:00 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_SS_GIYOUK     ("", 0x11A9),
Done.

2017-05-01 04:00 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_GIYOUK_SIOT   ("", 0x11AA),
Done.

2017-05-01 04:00 UTC, JeOhLee commented on app/src/main/java/kr/ac/kaist/team888/hangulcharacter/Hangul.java
> +  FIN_RIEUL_GIYOUK  ("", 0x11B0),
Done.

2017-05-01 09:04 UTC, hangpark approved these changes

2017-05-01 09:04 UTC, merged