[#48] Canvas Multiple Character Drawing
JeOhLee/MyLittleFont pull request #80
Opened 2017-05-26 15:30 UTC by JeOhLee

See [#48].

2017-05-27 04:10 UTC, bimak-server approved these changes
👍

2017-05-29 11:09 UTC, hangpark requested changes
(Coding convention) Spacing policy between casting type and value should be consistent.

2017-05-29 11:09 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontCanvasView.java
> +    int gapWidthSize = (int)(regionWidth * gap);
`int gapWidthSize = (int) (regionWidth * gap);`

2017-05-29 11:09 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontCanvasView.java
> +    int regionHeight = (int)(regionWidth / regionRatio);
`int regionHeight = (int) (regionWidth / regionRatio);`

2017-05-29 11:09 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontCanvasView.java
> +    int gapHeightSize = (int)(regionHeight * lineMargin);
`int gapHeightSize = (int) (regionHeight * lineMargin)`

2017-05-29 11:09 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontCanvasView.java
> +    int rowCount = (int)(Math.ceil(locatorsCount / (double)maxCol));
int rowCount = (int) (Math.ceil(locatorsCount / (double) maxCol));

2017-05-29 11:09 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/mylittlefont/FontCanvasView.java
> +    return (int)(inches * xdpi);
`return (int) (inches * xdpi);`

2017-05-29 11:38 UTC, hangpark approved these changes

2017-05-29 11:38 UTC, merged