[#50] Width Feature
JeOhLee/MyLittleFont pull request #83
Opened 2017-05-29 12:21 UTC by JeOhLee

see [#50].

2017-05-29 13:10 UTC, hangpark requested changes
`segment` is used for indicating a single chunk of curves from a joint to a next joint.

2017-05-29 13:10 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/locator/Locator.java
> +    for (ArrayList<BezierCurve> segmentData : skeletons) {
Change `segmentData` to `skeleton`.

2017-05-29 13:10 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/locator/Locator.java
> +      for (int i = 0; i < segmentData.size(); i++) {
Change `segmentData` to `skeleton`.

2017-05-29 13:10 UTC, hangpark commented on app/src/main/java/kr/ac/kaist/team888/locator/Locator.java
> +        segmentData.set(i,
Change `segmentData` to `skeleton`.

2017-05-29 13:13 UTC, bimak-server approved these changes
👍

2017-05-30 13:11 UTC, hangpark approved these changes

2017-05-31 14:38 UTC, merged